var OX_c8be5679 = '';
OX_c8be5679 += "<"+"div id=\"publyZoneContainer_16148\" style=\"width:728px\"><"+"div id=\"16148\" class=\"publyBannerLogo\" width=728 height=90><"+"/div><"+"script type=\"text/javascript\">if(typeof publyLogoMachina ==\"undefined\")document.write(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\" src=\"//scr\'+\'ipts.publy.net/mini_publylogo.js\"><"+"/scr\'+\'ipt>\');<"+"/script><"+"div id=\'pblyiol_16148\'><"+"/div>\n";
OX_c8be5679 += "<"+"script>\n";
OX_c8be5679 += "(function(w,h,s,g,gs){\n";
OX_c8be5679 += "var hbAdFF=document.createElement(\"iframe\");\n";
OX_c8be5679 += "hbAdFF.src=\"about:blank\";\n";
OX_c8be5679 += "hbAdFF.width=w;\n";
OX_c8be5679 += "hbAdFF.height=h;\n";
OX_c8be5679 += "hbAdFF.scrolling=\"no\";\n";
OX_c8be5679 += "hbAdFF.frameBorder=0;\n";
OX_c8be5679 += "hbAdFF.style.border=0;\n";
OX_c8be5679 += "hbAdFF.style.overflow=\"hidden\";\n";
OX_c8be5679 += "document.getElementById(\"pblyiol_16148\").appendChild(hbAdFF);\n";
OX_c8be5679 += "h=hbAdFF.contentDocument||hbAdFF.contentWindow.document;\n";
OX_c8be5679 += "h.open();h.writeln(\'<"+"!DOCTYPE html>\');\n";
OX_c8be5679 += "h.writeln(\'<"+"html>\');h.writeln(\'<"+"head><"+"base target=\"_top\"><"+"/head><"+"body>\');\n";
OX_c8be5679 += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">window.publyGAMPassbackAdunit=\"\'+g+\'\";window.publyGAMPassbackSizes=\"\'+gs+\'\";<"+"/scr\'+\'ipt>\');\n";
OX_c8be5679 += "h.writeln(\'<"+"div id=\"iol_ntwrk_16148\" zoneId=\"\'+s+\'\"><"+"/div>\');\n";
OX_c8be5679 += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">\');\n";
OX_c8be5679 += "h.writeln(\'var iol_pubId = \"publy/mundifrases\";\');\n";
OX_c8be5679 += "h.writeln(\'document.write(\\\'<"+"scr\\\'+\\\'ipt type=\"text/javasc\\\'+\\\'ript\" src=\"https://www.iolam.it/js/easyBid.js?pubId=\\\'+iol_pubId+\\\'\"><"+"\\/scr\\\'+\\\'ipt>\\\');\');\n";
OX_c8be5679 += "h.writeln(\'<"+"/scr\'+\'ipt>\');h.close();\n";
OX_c8be5679 += "})(728,90,3,\'/220249732/SP_Mundifrases/SP_Mundifrases_728x90_Inside_post_3\', \"[728, 90]\");\n";
OX_c8be5679 += "<"+"/script><"+"div id=\'beacon_820f313851\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://servedby.publy.net/lg.php?bannerid=22578&amp;campaignid=6037&amp;zoneid=16148&amp;loc=https%3A%2F%2Fwww.mundifrases.com%2Ftema%2Fpr%25C3%25A1ctica%2F&amp;referer=https%3A%2F%2Fwww.google.com%2F&amp;cb=820f313851\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
document.write(OX_c8be5679);
