var OX_60b3b05d = '';
OX_60b3b05d += "<"+"div id=\"publyZoneContainer_16162\" style=\"width:300px\"><"+"div id=\"16162\" class=\"publyBannerLogo\" width=300 height=250><"+"/div><"+"script type=\"text/javascript\">if(typeof publyLogoMachina ==\"undefined\")document.write(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\" src=\"//scr\'+\'ipts.publy.net/mini_publylogo.js\"><"+"/scr\'+\'ipt>\');<"+"/script><"+"div id=\'pblyiol_16162\'><"+"/div>\n";
OX_60b3b05d += "<"+"script>\n";
OX_60b3b05d += "(function(w,h,s,g,gs){\n";
OX_60b3b05d += "var hbAdFF=document.createElement(\"iframe\");\n";
OX_60b3b05d += "hbAdFF.src=\"about:blank\";\n";
OX_60b3b05d += "hbAdFF.width=w;\n";
OX_60b3b05d += "hbAdFF.height=h;\n";
OX_60b3b05d += "hbAdFF.scrolling=\"no\";\n";
OX_60b3b05d += "hbAdFF.frameBorder=0;\n";
OX_60b3b05d += "hbAdFF.style.border=0;\n";
OX_60b3b05d += "hbAdFF.style.overflow=\"hidden\";\n";
OX_60b3b05d += "document.getElementById(\"pblyiol_16162\").appendChild(hbAdFF);\n";
OX_60b3b05d += "h=hbAdFF.contentDocument||hbAdFF.contentWindow.document;\n";
OX_60b3b05d += "h.open();h.writeln(\'<"+"!DOCTYPE html>\');\n";
OX_60b3b05d += "h.writeln(\'<"+"html>\');h.writeln(\'<"+"head><"+"base target=\"_top\"><"+"/head><"+"body>\');\n";
OX_60b3b05d += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">window.publyGAMPassbackAdunit=\"\'+g+\'\";window.publyGAMPassbackSizes=\"\'+gs+\'\";<"+"/scr\'+\'ipt>\');\n";
OX_60b3b05d += "h.writeln(\'<"+"div id=\"iol_ntwrk_16162\" zoneId=\"\'+s+\'\"><"+"/div>\');\n";
OX_60b3b05d += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">\');\n";
OX_60b3b05d += "h.writeln(\'var iol_pubId = \"publy/mundifrases\";\');\n";
OX_60b3b05d += "h.writeln(\'document.write(\\\'<"+"scr\\\'+\\\'ipt type=\"text/javasc\\\'+\\\'ript\" src=\"https://www.iolam.it/js/easyBid.js?pubId=\\\'+iol_pubId+\\\'\"><"+"\\/scr\\\'+\\\'ipt>\\\');\');\n";
OX_60b3b05d += "h.writeln(\'<"+"/scr\'+\'ipt>\');h.close();\n";
OX_60b3b05d += "})(300,600,2,\'/220249732/SP_Mundifrases/SP_Mundifrases_300x600_paginazione_desktop\', \"[300, 600]\");\n";
OX_60b3b05d += "<"+"/script><"+"div id=\'beacon_ca3c8b9790\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://servedby.publy.net/lg.php?bannerid=22585&amp;campaignid=6037&amp;zoneid=16162&amp;loc=https%3A%2F%2Fwww.mundifrases.com%2Ftema%2Fpr%25C3%25A1ctica%2F&amp;referer=https%3A%2F%2Fwww.google.com%2F&amp;cb=ca3c8b9790\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
document.write(OX_60b3b05d);
