var OX_935a8f3b = '';
OX_935a8f3b += "<"+"!-- Skin Mundifrases.com S -->\n";
OX_935a8f3b += "<"+"script type=\"text/javascript\" >\n";
OX_935a8f3b += "/* 3rd party tracing URL */\n";
OX_935a8f3b += "var aplus_referrer = \"www.mundifrases.com\";\n";
OX_935a8f3b += "<"+"/script>\n";
OX_935a8f3b += "<"+"SCRIPT SRC=\"https://d62mrph0xm5hi.cloudfront.net/ssl/75641\" TYPE=\"text/javascript\"><"+"/SCRIPT>\n";
OX_935a8f3b += "<"+"ins data-revive-zoneid=\"16200\" data-revive-id=\"58d568592263780e1c93f31ea32143c6\"><"+"/ins>\n";
OX_935a8f3b += "<"+"script async src=\"//servedby.publy.net/asyncjs.php\"><"+"/script>\n";
OX_935a8f3b += "<"+"div><"+"/div>\n";
OX_935a8f3b += "<"+"!-- VIP -->\n";
OX_935a8f3b += "<"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OX_935a8f3b += "var m3_u = (location.protocol==\'https:\'?\'https://servedby.publy.net/ajs.php\':\'http://servedby.publy.net/ajs.php\');\n";
OX_935a8f3b += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OX_935a8f3b += "if (!document.MAX_used) document.MAX_used = \',\';\n";
OX_935a8f3b += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OX_935a8f3b += "document.write (\"?zoneid=16203\");\n";
OX_935a8f3b += "document.write (\'&amp;cb=\' + m3_r);\n";
OX_935a8f3b += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OX_935a8f3b += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OX_935a8f3b += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OX_935a8f3b += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OX_935a8f3b += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OX_935a8f3b += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OX_935a8f3b += "document.write (\"\'><"+"\\/scr\"+\"ipt>\");\n";
OX_935a8f3b += "//]]>--><"+"/script><"+"div id=\'pblyiol_16140\'><"+"/div>\n";
OX_935a8f3b += "<"+"script>\n";
OX_935a8f3b += "(function(w,h,s,g,gs){\n";
OX_935a8f3b += "var hbAdFF=document.createElement(\"iframe\");\n";
OX_935a8f3b += "hbAdFF.src=\"about:blank\";\n";
OX_935a8f3b += "hbAdFF.width=w;\n";
OX_935a8f3b += "hbAdFF.height=h;\n";
OX_935a8f3b += "hbAdFF.scrolling=\"no\";\n";
OX_935a8f3b += "hbAdFF.frameBorder=0;\n";
OX_935a8f3b += "hbAdFF.style.border=0;\n";
OX_935a8f3b += "hbAdFF.style.overflow=\"hidden\";\n";
OX_935a8f3b += "document.getElementById(\"pblyiol_16140\").appendChild(hbAdFF);\n";
OX_935a8f3b += "h=hbAdFF.contentDocument||hbAdFF.contentWindow.document;\n";
OX_935a8f3b += "h.open();h.writeln(\'<"+"!DOCTYPE html>\');\n";
OX_935a8f3b += "h.writeln(\'<"+"html>\');h.writeln(\'<"+"head><"+"base target=\"_top\"><"+"/head><"+"body>\');\n";
OX_935a8f3b += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">window.publyGAMPassbackAdunit=\"\'+g+\'\";window.publyGAMPassbackSizes=\"\'+gs+\'\";<"+"/scr\'+\'ipt>\');\n";
OX_935a8f3b += "h.writeln(\'<"+"div id=\"iol_ntwrk_16140\" zoneId=\"\'+s+\'\"><"+"/div>\');\n";
OX_935a8f3b += "h.writeln(\'<"+"scr\'+\'ipt type=\"text/javascr\'+\'ipt\">\');\n";
OX_935a8f3b += "h.writeln(\'var iol_pubId = \"publy/mundifrases\";\');\n";
OX_935a8f3b += "h.writeln(\'document.write(\\\'<"+"scr\\\'+\\\'ipt type=\"text/javasc\\\'+\\\'ript\" src=\"https://www.iolam.it/js/easyBid.js?pubId=\\\'+iol_pubId+\\\'\"><"+"\\/scr\\\'+\\\'ipt>\\\');\');\n";
OX_935a8f3b += "h.writeln(\'<"+"/scr\'+\'ipt>\');h.close();\n";
OX_935a8f3b += "})(728,90,3,\'/220249732/SP_Mundifrases/SP_Mundifrases_728x90_leaderboard//masthead\', \"[[728, 90], [970, 250]]\");\n";
OX_935a8f3b += "<"+"/script><"+"div id=\'beacon_d4e2c3875e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://servedby.publy.net/lg.php?bannerid=22571&amp;campaignid=6037&amp;zoneid=16140&amp;loc=https%3A%2F%2Fwww.mundifrases.com%2Ftema%2Fpr%25C3%25A1ctica%2F&amp;referer=https%3A%2F%2Fwww.google.com%2F&amp;cb=d4e2c3875e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(OX_935a8f3b);
